collections_dir: works

collections:
  book-covers:
    output: true
  characters:
    output: true
  packages:
    output: true
  nsfw:
    output: true
  portfolio-book-covers:
    output: true
  portfolio-characters:
    output: true
  portfolio-packages:
    output: true
  portfolio-nsfw:
    output: true
#  customs:
#  addons:
     
defaults:
  - scope:
      path: ""
      type: "book-covers"
    values:
      layout: "portfolio-item"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "portfolio-item"
  - scope:
      path: ""
      type: "nsfw"
    values:
      layout: "portfolio-item"
  - scope:
      path: ""
      type: "packages"
    values:
      layout: "portfolio-item"
  - scope:
      path: ""
      type: "portfolio-book-covers"
    values:
      layout: "portfolio-item"
  - scope:
      path: ""
      type: "portfolio-characters"
    values:
      layout: "portfolio-item"
  - scope:
      path: ""
      type: "portfolio-nsfw"
    values:
      layout: "portfolio-item"
  - scope:
      path: ""
      type: "portfolio-packages"
    values:
      layout: "portfolio-item"
  - scope:
      path: ""
    values:
      layout: "default"
