packages:
  - name: Platform Package
    price: 90
    items:
      - Ebook
      - Artwork
      - PNG Typography
      - FB Banner
      - IG Promo
      - 3D Mockups

  - name: Standard Package
    price: 100
    items:
      - Ebook
      - Paperback
      - Artwork
      - PNG Typography
      - 3D Mockups
      - up to 5 stocks
      
  - name: Budget Package
    highlight: true
    price: 150
    items:
      - Ebook
      - Paperback
      - Artwork
      - PNG Typography
      - 3 Stock images
      - 3D Mockups
      - Bookmarks
      - Banner
      - up to 5 stocks

  - name: Premium Package
    price: 200
    items:
      - Ebook
      - Paperback
      - Artwork
      - PNG Typography
      - 3 Stock images
      - 3D Mockups
      - Bookmarks
      - 1 Character included
      - up to 10 stocks

  - name: Exclusive Package
    price: 280
    items:
      - Ebook
      - Paperback
      - Artwork
      - PNG Typography
      - 3 Stock images
      - 3D Mockups
      - Bookmarks
      - 2 Characters
      - Banner
      - IG Promo
      - Unlimited stock usage


other:
  - name: Character Design
    items:
      - name: Half body character
        price: 60
      - name: Full body character
        price: 100
  - name: Packages
    items:
      - name: Ten characters half body
        price: 480
      - name: Ten characters full body
        price: 700
